config/routes.rb
Rails.application.routes.draw do
   root 'entries#index'
   scope '/blogs' do
     post '/update_all_blogs' => 'blogs#update_all_blogs', as: :blogs_update_all_blogs
     post '/:id/download_newest_entries' => 'blogs#download_newest_entries', as: :blog_download_newest_entries
   end
   resources :blogs
   resources :entries, only: [:index, :show, :destroy]
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :entries, dependent: :destroy
  
  after_create :download_entries_after_blog_create

  #grab each feed
  #update feed articles - download_entries_after_blog_create
  
  def update_feed!
    @newest_entry = entries.order(published: :desc).first

    download_success_date = lambda { |url, feed|
      feed.entries.each do |entry|
         next unless !@newest_entry || entry.published > @newest_entry.published
         add_new_entry_from_feed(entry)
      end
    }
    Feedjira::Feed.fetch_and_parse(
      url,
      on_success: download_success_date,
      on_failure: download_failure
    )
  end

  def download_all_entries!
    Feedjira::Feed.fetch_and_parse(
      url,
      on_success: download_success,
      on_failure: download_failure
    )
  end

  def download_newest_entries!(number)
    return false if number == 0
    on_success_number = lambda { |url, feed|
      feed.entries[0..number - 1].each do |entry|
        add_new_entry_from_feed(entry)
      end
    }
    feed = Feedjira::Feed.fetch_and_parse(
      url,
      on_success: on_success_number,
      on_failure: download_failure
    )
  end

  def download_newest_entry!
    download_newest_entries!(1)[0]
  end

  def self.update_all_blogs
    Blog.all.each do |blog|
      blog.update_feed!
    end
  end

  def download_entries_after_blog_create
    download_newest_entries!(5)
  end

  private

  def add_new_entry_from_feed(entry)
    db_entry = Entry.create_entry_from_feed(entry)
    db_entry.blog_id = id
    db_entry.save
  end

  def download_success
    lambda { |url, feed|
      feed.entries.each do |entry|
        add_new_entry_from_feed(entry)
      end
    }
  end

  def download_failure
    lambda { |curl, err|
      logger.error "Downloading #{curl} failed due to #{error}"
    }
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :blog

  def self.create_entry_from_feed(entry)
    new_entry = Entry.new(title: entry.title,
                          author: entry.author,
                          content: check_content(entry),
                          published: entry.published,
                          url: entry.url,
                         )
    new_entry
  end

  private

  def self.check_content(entry)
    return entry.content if entry.content
    return entry.summary if entry.summary
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
    @entries = @blog.entries.all.order(published: :asc)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)
    redirect_to blogs_path
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    redirect_to blog_path(@blog)
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  def download_newest_entries
    @blog = Blog.find(params[:id])
    @blog.download_newest_entries!(params[:download_entries][:entries_num].to_i)
    redirect_to blog_path(@blog)
  end

  def update_all_blogs
    Blog.update_all_blogs
    redirect_to blogs_path
  end
  private

  def blog_params
    params.require(:blog).permit(:url)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @entries = Entry.all.order(published: :desc)
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to entries_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/edit.html.haml
=form_for @blog do |f|
  =f.label :url
  =f.text_field :url
  =f.submit 'Submit'

app/views/blogs/index.html.haml
-@blogs.each do |blog|
  =link_to 'blog', blog_path(blog)

app/views/blogs/new.html.haml
=form_for @blog do |f|
  =f.label :url
  =f.text_field :url
  =f.submit 'Submit'

app/views/blogs/show.html.haml
=@blog.url
=form_for :download_entries, url: :blog_download_newest_entries do |f|
  =f.label :entries_num, 'Number of entries to download'
  =f.number_field :entries_num
  =f.submit 'Download'
%ol
  -@entries.each do |entry|
    %li
      =render 'entries/entry', entry: entry

app/views/entries/_entry.haml
%ul
  %li
    %h4
      =entry.title
    =link_to entry.url, entry.url
    =entry.author
    =entry.published
    %p
      =truncate_html(entry.content, length: 300, omission: '...(continued)')
      

app/views/entries/index.html.haml
%ol
  -@entries.each do |entry|
    %li
      =render 'entry', entry: entry

app/views/entries/show.html.haml
=render 'entry', entry: @entry

app/views/layouts/_navigation.haml
=link_to 'New blog', new_blog_path
=link_to 'Blogs index', blogs_path
=link_to 'Entries index', entries_path
=link_to 'Update all blogs', blogs_update_all_blogs_path, method: :post

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FeedjiraWithRails
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    %br
    = yield